import { Navigate, Outlet } from "react-router-dom";
import useStableSession from "../hooks/useStableSession";
import authClient from "../authClient";

const RequireUsername = () => {
  const { data: session, isPending } = useStableSession();
  //const { data: session, isPending } = authClient.useSession();

  if (isPending) {
    return (
      <div className="fixed inset-0 z-50 grid place-items-center bg-[#0b0b0b] text-[#e7c49d]">
        LOADING...
      </div>
    );
  }

  // Not logged in, guest already has their username generated by server so proceed to outlet
  if (!session?.user) {
    return <Outlet />;
  }

  // Logged in, but no username, need a username to be able to play
  if (!session.user.username) {
    return <Navigate to="/choose-username" replace />;
  }

  // Logged in and has a username
  return <Outlet />;
};

export default RequireUsername;
