import { Navigate, Outlet } from "react-router";
import useStableSession from "../../hooks/useStableSession";
import authClient from "../../authClient";

const RequireUsername = () => {
  const { session, isPending } = useStableSession();
  //const { data: session, isPending } = authClient.useSession();

  if (isPending) {
    return (
      <main className="min-h-[calc(100vh-72px)] grid place-items-center bg-[#0b0b0b] font-mono text-[#e7c49d]">
        LOADING...
      </main>
    );
  }

  // Not logged in, guest already has their username generated by server so proceed to outlet
  if (!session?.user) {
    return <Outlet />;
  }

  // Logged in, but no username, need a username to be able to play
  if (session?.user && !session.user?.username) {
    return <Navigate to="/choose-username" replace />;
  }

  // Logged in and has a username
  return <Outlet />;
};

export default RequireUsername;
