import { Navigate, Outlet } from "react-router";
import useStableSession from "../../hooks/useStableSession";
import toast from "react-hot-toast";

const RequireUsername = () => {
  const { session, isPending, error, persistentError } = useStableSession();

  if (isPending) {
    return (
      <main className="min-h-[calc(100vh-72px)] grid place-items-center bg-[#0b0b0b] font-mono text-[#e7c49d]">
        LOADING...
      </main>
    );
  }

  if (error) {
    return (
      <main className="min-h-[calc(100vh-72px)] grid place-items-center bg-[#0b0b0b] font-mono text-[#e7c49d]">
        {persistentError
          ? "SESSION ERROR — STILL TRYING..."
          : "SESSION ERROR — RETRYING..."}
      </main>
    );
  }

  // Not logged in, guest already has their username generated by server so proceed to outlet
  if (!session?.user) {
    return <Outlet />;
  }

  // Logged in, but no username, need a username to be able to play
  if (session?.user && !session.user?.username) {
    toast.error(
      "You need a username to access this page. Redirecting to choose username.",
    );
    return <Navigate to="/choose-username" replace />;
  }

  // Logged in and has a username
  return <Outlet />;
};

export default RequireUsername;
